### ISSUE TITLE
Modification for DuoRacer

### ISSUE THREAD

**Issue by pinkflozd** [fatyogi/epever-upower-tracer#15]
Hello. I have a Epever DuoRacer (https://www.epever.com/product/duoracer-10-30a-mppt-charge-controller-dual-battery/), that doesn't have a DC load but instead charges a secondary/start battery.
Any hints on what to change to show the secondary battery voltage? Secondary charging watts and amps show through DCamps and DCwatt but secondary battery voltage doesn't show through DCvolt. 
it probably has a different register? how can i read it?

overall it works great on my charge controller

**Comment by fatyogi** [comment]
I suggest you contact EPever and request  the list of registers for this
controller.

// Laconic style, sent from my phone
