### ISSUE TITLE
Support Tracer AN series (e.g. 2206) bulk register write

### ISSUE THREAD

**Issue by hrford** [fatyogi/epever-upower-tracer#3]
I would like to set values for my shiny new LiFePo4 12V 100Ah battery.
The 3 factory programmed voltage settings do not suit, so user-defined settings must be used.

To set the user-defined settings, the Tracer AN series requires registers to be set in bulk and not individually.
I've expanded the SolarTracer.py locally to prove this can be done:

`values = up.readParams(OverVoltageDisconnect, 12)
MinimalModbus debug mode. Will write to instrument (expecting 29 bytes back): 01 03 90 03 00 0C 98 CF (8 bytes)
MinimalModbus debug mode. Clearing serial buffers for port /dev/ttyUSB2
MinimalModbus debug mode. Sleeping 1.19 ms before sending. Minimum silent period: 1.75 ms, time since read: 0.56 ms.
MinimalModbus debug mode. Response from instrument: 01 03 18 06 40 05 DC 05 DC 05 B4 05 A0 05 64 05 28 04 EC 04 C4 04 B0 04 56 04 24 97 06 (29 bytes), roundtrip time: 0.1 ms. Timeout for reading: 1200.0 ms.`

`print(values)
[1600, 1500, 1500, 1460, 1440, 1380, 1320, 1260, 1220, 1200, 1110, 1060]`

`up.writeParams(OverVoltageDisconnect, values)
MinimalModbus debug mode. Will write to instrument (expecting 8 bytes back): 01 10 90 03 00 0C 18 06 40 05 DC 05 DC 05 B4 05 A0 05 64 05 28 04 EC 04 C4 04 B0 04 56 04 24 6F 11 (33 bytes)
MinimalModbus debug mode. Clearing serial buffers for port /dev/ttyUSB2
MinimalModbus debug mode. Sleeping 0.59 ms before sending. Minimum silent period: 1.75 ms, time since read: 1.16 ms.
MinimalModbus debug mode. Response from instrument: 01 10 90 03 00 0C 1D 0C (8 bytes), roundtrip time: 0.1 ms. Timeout for reading: 1200.0 ms.`

**Comment by hrford** [comment]
Nice work. I've solved this issue on another project and will likely backport it here.

**Comment by fatyogi** [comment]
> For future readers of this issue, [my post on diysolarforum.com](https://diysolarforum.com/threads/setting-registers-in-epever-controller-with-python.25406/#post-300158) might be of interest. (It's using pymodbus, but dives pretty deep into reverse-engineering which registers are getting set by the MT-50 display.)

Thank you for that @symbioquine - will update the code here to include your research. Do you have presets of values for all types of batteries? The one of interest of course is the Lithium (e.g. LiFePO4)

**Comment by symbioquine** [comment]
@fatyogi The default values are in the manual iirc

**Comment by fatyogi** [comment]
olaf@solarhost:~/epever-upower-tracer $ ./getTracerSettings.py 
Local time: 18:17:02
UTC timestamp: 2023-03-13 05:17:02.129773

BatteryType              : USER(0)
BatteryCapacity          : 300 Ah
HighVoltageDisconnect    : 15.0
ChargingLimitVoltage     : 14.6
OverVoltageReconnect     : 14.2
EqualizationVoltage      : 14.0
BoostVoltage             : 13.8
FloatVoltage             : 13.8
BoostReconnectVoltage    : 13.2
LowVoltageReconnect      : 12.4
UnderVoltageReconnect    : 12.0
UnderVoltageWarning      : 11.6
LowVoltageDisconnect     : 10.8
DischargingLimitVoltage  : 10.4
