### ISSUE TITLE
compile with make gives errors

### ISSUE THREAD

**Issue by Maikeleg** [fatyogi/epever-upower-tracer#4]
Problem running make on 5.15.61-v7+ #1579 SMP Fri Aug 26 11:10:59 BST 2022 armv7l GNU/Linux
This is Raspbian OS Bullseye
"**After installing the headers be sure to sudo bundle then sudo make. The resulting ...**"
sudo bundle: command not found, cannot find what this does
make gives 9 errors, i found that it seems to be solved using the [xr_usb_serial_common.c](https://github.com/kasbert/epsolar-tracer/blob/master/xr_usb_serial_common-1a/xr_usb_serial_common.c)
```
mv ./xr_usb_serial_common-1a/xr_usb_serial_common.c ./xr_usb_serial_common-1a/xr_usb_serial_common.c.org
cp ../../epsolar-tracer/xr_usb_serial_common-1a/xr_usb_serial_common.c .
```

executing make now compiles without errors

**Comment by fatyogi** [comment]
Hello @Maikeleg - sincere apologies for the delay resolving this. I finally came across the same problem upgrading to Linux 5.x. There is another driver directory now where you can find the new version of the driver: 
/xr_usb_serial_common-1a-linux-3.6+

After installing the Linux kernel headers all you need to do is to recomple and install the driver using make:

# cd xr_usb_serial_common-1a-linux-3.6+/
# make
# make install
