### ISSUE TITLE
Cable type

### ISSUE THREAD

**Issue by shandshellin** [fatyogi/epever-upower-tracer#8]
Will this work with a factoryusb cable that came with or is there a wiring diagram for making a custom cable? I have one factory cable and a couple of usb to rs485 adapter cables with ftdi chips, would be nice to use some of those.

**Comment by shandshellin** [comment]
Also, i am using a venusos build to monitor the bms's over bluetooth via a webpage. Have you played with that at all? Thinking about adding this to that image if possible as the pi3 should be able to handle it. Thoughts?

**Comment by fatyogi** [comment]
> Will this work with a factoryusb cable that came with or is there a wiring diagram for making a custom cable? I have one factory cable and a couple of usb to rs485 adapter cables with ftdi chips, would be nice to use some of those.

I am not sure about custom cables and their wiring. When I wrote a module for SD320 I had to re-wire pins on my Epever cable so they match those on the SD320. You need to check the doco for the cable.

> Also, i am using a venusos build to monitor the bms's over bluetooth via a webpage. Have you played with that at all? Thinking about adding this to that image if possible as the pi3 should be able to handle it. Thoughts?

I would love to do this, I have a JBD (Overkill etc.) BMS which can be monitored over Bluetooth. It is a matter of finding the protocol description or better still - a Python library that talks to these devices. I haven’t yet looked into this matter so cannot really advice on that. All loggers within this project is a simple Serial port communication.

**Comment by fatyogi** [comment]
There seems to be a Bluetooth monitoring project here - https://github.com/tgalarneau/bms

**Comment by shandshellin** [comment]
venusos runs on a rpi and uses the junky jbd bms's, works ok. maybe i'll see if it will let me install this. I use prometheus instead of influxdb

**Comment by shandshellin** [comment]
I recall this guy saying that the bluetooth would only work with jbd as per his driver but you can still use usb to connect the bms to the pi for web based monitoring.

**Comment by fatyogi** [comment]
You can, only if you replace the BT module on JBD with their UART module.
So it is either Bluetooth or USB.

// Laconic style, sent from my phone

**Comment by shandshellin** [comment]
mine have a usb and rs485 port on the bms. usb is the bt adapters.

**Comment by gimi-q** [comment]
I have a question about cable type aswell.
 
I have the cqrobot usb cable : http://www.cqrobot.wiki/index.php/USB_to_RS422_or_RS485_Adapters_Cable_SKU:_CQRCK701_CQRCK702_CQRCK703

would this be suitable? everything works for me on my Pi4 but the values are all -2. I am wondering if its the cable or something else I am doing wrong. Any advice or help would be appreciated. Thanks for putting this together. I am so close, yet so far away :)

**Comment by fatyogi** [comment]
@gimi-q -2 values means that the connection fails. This code assumes that you use Exar adapter, which presents itself as /dev/ttyXRUSBx. Your Cqrobot adapter is going to present itself to the OS as a different device. You will not see it as /dev/ttyXRUSB0 but something else, so you'll have to change the logger to connect to your device instead.
First, without the adapter attached, do 'ls -la /dev/tty*'. Then attach the adapter and run the command again - you will see your new device in the list - change the code to connect to this device. If you are using the Tracer logger - the device name is set in the configuration file.

**Comment by Rob-bb** [comment]
I purchased this cable from Ali express, it shows up on the raspberry as "QinHeng Electronics USB Single Serial"

https://www.aliexpress.com/item/32972908976.html?spm=a2g0o.order_list.order_list_main.16.324b1802R2b24o

I changed the tracer port to /dev/ttyACM0 and it connected and appears to be getting results without any drivers needed connected to a EPEVER Tracer 3906 BP sold under the Ridge Ryder brand at Super Cheap Auto in New Zealand and Australia 

```/epever-upower-tracer/logtracer.py 
[{'measurement': 'solar', 'time': datetime.datetime(2024, 1, 1, 7, 30, 48, 652493), 'fields': {'PVvolt': 14.8, 'PVamps': 0.01, 'PVwatt': 0.26, 'BAvolt': 13.48, 'BAamps': 0.02, 'BAwatt': 0.26, 'DCvolt': 13.48, 'DCamps': 0.0, 'DCwatt': 0.0, 'BAtemp': 19.06, 'CTtemp': 19.06, 'BAperc': 85.0, 'BAcurr': 0.0002}}]

Process finished with exit code 0```

**Comment by fatyogi** [comment]
It looks like we can close this issue. Thanks everyone!
