### ISSUE TITLE
There are some problems and setup questions

### ISSUE THREAD

**Issue by T-Shilov** [fatyogi/epever-upower-tracer#9]
Hello Olaf,

I really liked your beautiful project! 👍
And I decided to use it for my **EP EVER EPSolar Tracer 2210AN** solar controller.
The installation went without any problems, and I got this result:

![Dashboard](https://github.com/fatyogi/epever-upower-tracer/assets/61428202/5b4fb75f-4200-4dc9-be90-b807ea0fd51d)

Unfortunately, the data received does not correspond to real data and is static.
What else should I do to get the correct results?

**Comment by fatyogi** [comment]
First, verify the data is actually coming from the device. If you run the Tracer logger in Linux command line - it will produce the output of the values it is reading.

Second, verify the data is stored in the database - run the influx command line tool and do 'select * from solar;' query. It should show the values read and stored previously.

If these all work - check out the Grafana Dashboard and make sure you are extracting the correct fields from InfluxDB

**Comment by T-Shilov** [comment]
Please:
```
root@raspberrypi:/home/user/GIT/epever-upower-tracer# python3 logtracer.py
[{'measurement': 'solar', 'time': datetime.datetime(2024, 5, 29, 14, 28, 36, 398070), 'fields': {'PVvolt': 14.68, 'PVamps': 0.64, 'PVwatt': 9.49, 'BAvolt': 13.19, 'BAamps': 0.72, 'BAwatt': 9.49, 'DCvolt': 13.19, 'DCamps': 0.0, 'DCwatt': 0.0, 'BAtemp': 28.08, 'CTtemp': 30.5, 'BAperc': 59.0, 'BAcurr': 0.0072}}]
root@raspberrypi:/home/user/GIT/epever-upower-tracer# 
```

```
root@raspberrypi:/home/user/GIT/epever-upower-tracer# influx
Connected to http://localhost:8086 version 1.8.10
InfluxDB shell version: 1.8.10
> 
> select * from solar;
ERR: database name required
Warning: It is possible this error is due to not setting a database.
Please set a database with the command "use <database>".
> 
```

**Comment by fatyogi** [comment]
From what I see here there is a good capture of data from the device. As
you can observe, the values coming in make perfect sense:

Solar power voltage: 14.87V
Battery voltage: 13.19V

And so on.

Your next step is to run influx, then connect to your database ‘use solar;’
and then run the query ‘select * from solar;’ - here you should see some
historic values stored in the database previously.

Once you see them - jump into the dashboard and look at your queries there.
Make sure you display the right fields from the DB - e.g the graph query
for Battery Voltage should select BAvolt.

This part should work right away if your data is captured and stored
correctly.

Just a little reminder - as it says in the description, this project
assumes some basic knowledge of Influx and Grafana. I’d have a look at the
documentation for both and see how to query Influx and how to configure the
Dashboard.

Have a little play, see how it goes. Good luck 👍

Thanks,
Olaf

**Comment by T-Shilov** [comment]
Thank you, Olaf.
Tell me please, can your project display and store energy?
In kilowatt hours.

**Comment by T-Shilov** [comment]
Hello Olaf,

Energy monitoring is the calculation of Solar Panels' solar energy and saving it every minute, hour, week, year and displaying it on the screen in the same way as other parameters.
To do this, it is enough to multiply the voltage by the current.

I'm still using the project for this [Blynk](https://blynk.io)
Here is his screen:

![Blynk cloud - Tracer 2210AN  (week)](https://github.com/fatyogi/epever-upower-tracer/assets/61428202/675c0551-f766-4a74-9355-5098664fd85b)
(there is a combination of English and Ukrainian languages here)

But I don't like Blink because it's too feature-rich and redundant and it's in the cloud. I prefer a simple local project like yours.

Therefore, I would like to switch to your beautiful and pleasant project.
But to do this, I need to correct the errors that have arisen and add counting and demonstration of energy.

I hope for your help.

**Comment by US1GHQ** [comment]
Good day i have some questions
It seems that this software does not read all the data from Epower, that is why the readings are incorrect.
Does he have one request for a solar controller in Python or several?

I have some controller and your software really liked it, but i have incorrect values too.
Sorry for my English.

**Comment by Tamila-2017** [comment]
Hi everyone,
I also need an electricity calculation.

**Comment by fatyogi** [comment]
Hi (sorry still don’t have your name)

I see what you mean now.

The Epever controller has these statistical values stored, you do not need
to do any calculation for that - just read the values. For example, Kwh2d
is the value for the energy generated today.

In the SolarTracer.py module you will find the sub/method to read these
statistical value.

If you want to display the values - just add another Graph or Text field in
Graphana and query this value.

In my own dashboard I do that. If you want I can send you my own
dashboard’s configuration.

// Laconic style, sent from my phone

**Comment by fatyogi** [comment]
> Hello Olaf,
> 
> Energy monitoring is the calculation of Solar Panels' solar energy and saving it every minute, hour, week, year and displaying it on the screen in the same way as other parameters. To do this, it is enough to multiply the voltage by the current.
> 
> I'm still using the project for this [Blynk](https://blynk.io) Here is his screen:
> 
> ![Blynk cloud - Tracer 2210AN (week)](https://private-user-images.githubusercontent.com/61428202/335193717-675c0551-f766-4a74-9355-5098664fd85b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMDkxNTMsIm5iZiI6MTcxNzEwODg1MywicGF0aCI6Ii82MTQyODIwMi8zMzUxOTM3MTctNjc1YzA1NTEtZjc2Ni00YTc0LTkzNTUtNTA5ODY2NGZkODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDIyNDA1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NzhkZTQzNjIxN2I0NGI5YzA0MDlkOWI4MzhmNTI2OWE3MWVmMTMxZjJmNzViMjZjNzU2MjYzNTllZjJjNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nvdMs3OBIVDS8BwFik9VbOAp9_aeDzx0paFb6wKt4As) (there is a combination of English and Ukrainian languages here)
> 
> But I don't like Blink because it's too feature-rich and redundant and it's in the cloud. I prefer a simple local project like yours.
> 
> Therefore, I would like to switch to your beautiful and pleasant project. But to do this, I need to correct the errors that have arisen and add counting and demonstration of energy.
> 
> I hope for your help.

@T-Shilov - here is my dashboard

<img width="1450" alt="image" src="https://github.com/fatyogi/epever-upower-tracer/assets/20548667/559062f2-76c0-44e3-9d75-0a1e131d9385">

As you can see, there are statistical values:

- Generated Today
- Consumed Today
- Total Generated
- Generated This Year
- Total OUT

**Comment by fatyogi** [comment]
@Tamila-2017 , @T-Shilov , @US1GHQ 

Thank you for providing the feedback. Now I see where the problem lies. 

Last time I updated the repository, I forgot to update the README - the instructions.
In my last rewrite of the SolarTracer.py module I SEPARATED the reading of Current values and Statistical values into two separate loggers. We now have the:

- logtracer.py - it reads the current values, and
- logtracerstats.py - it reads the statistical values

if you need the statistical values (such as the energy accumulated/generated today, over last month, year and in total) you should add this other logger into cron, and this logger does not have to run every minute. For example, in this crontab here we have the current values logger running every minute, and the Statistics logger running every hour:

* * * * *  cd /home/pi/epever-upower-tracer && ./logsdmtracer.py > /dev/null
0 * * * *  cd /home/pi/epever-upower-tracer && ./logtracerstats.py > /dev/null

Please re-read the instrictions - I updated them to reflect them.

The dashboard posted earlier in this thread can be downloaded from  grafana/AC_DC_SolarDashboard.json

I think we can now close this issue.

**Comment by Soltuser** [comment]
> If you want I can send you my own
dashboard’s configuration.

Yes, it would be very interesting. Please send it.

**Comment by T-Shilov** [comment]
Hello Olaf,

> Please re-read the instrictions - I updated them to reflect them.

Thanks for your corrections! I hope they will fix the problem with incorrect parameter readings.

Olaf, please tell me, what is the load  your project on Raspberry?

Will Raspberry [**Pi Zero 2 W**](https://www.raspberrypi.com/products/raspberry-pi-zero-2-w/) be able to cope with this task?

**Comment by fatyogi** [comment]
Hi T-Shilov,

I have an ancient Pi 3, which is working fine for a few years now. It runs
Grafana, Infux and the logger that picks up the values from two devices
once a minute. If your Pi is of later generation - I believe it should be
fine, although I have no experience with the Zero model.

// Laconic style, sent from my phone

**Comment by T-Shilov** [comment]
Hello Olaf,

Thank you, it's just wonderful! 👍

I'm also using the ancient Pi 3 right now. But I want to switch to Pi Zero because its the current consumption is very small, only **0.12** A 😃
So Zero is much more economical than Pi 3, and this is very important for the solar.

**Comment by fatyogi** [comment]
Hi T-Shilov,

Did you include another logger into your crontab? As per the instructions,
to read the statistical values you have to run another logger.

Is your Readme file up to date?

See this under “Setting up a crown job….”, step 5:

   1.

   if you need the statistical values (such as the energy
   accumulated/generated today, over last month, year and in total) you should
   add another logger into cron, and this logger DOES NOT have to run every
   minute.

   For example, here we have the Statistics logger running every hour:

   0 * * * * cd /home/pi/epever-upower-tracer && ./logtracerstats.py >
   /dev/null


Kind regards
Olaf

// Laconic style, sent from my phone

**Comment by fatyogi** [comment]
Here are the two lines you need in your crontab to acquire both current and statistical values. First line pulls current values every minute. Second line pulls statistical values such as energy accumulated etc. every hour.

* * * * *  cd /home/pi/epever-upower-tracer && ./logtracer.py > /dev/null
0 * * * *  cd /home/pi/epever-upower-tracer && ./logtracerstats.py > /dev/null

**Comment by fatyogi** [comment]
Once you have your Statistical script running, you will see another measurement called `solar_stats` in InfluxDB

These are the values you can select from there, when you build your Grafana query:

DCkwh2d - DC power consumed today
DCkwhTT - ... consumed in total
DCkwhTY - ... consumed This Year
DCkwhTm - ... consumed This Month

And for the generation you have these values consequently:

PVkwh2d - generated today ... and so on
PVkwhTT
PVkwhTY
PVkwhTm

**Comment by Tamila-2017** [comment]
Hi,
Hooray, the instruction has noticeably improved, respect! 

And tell me, is it possible to make guest access to the dashboard?
 So that guest can see her readings, but so that he cannot change her settings.

**Comment by Tamila-2017** [comment]
Hi,
Hooray, the instruction has noticeably improved, respect! 

And tell me, is it possible to make guest access to the dashboard?
 So that guest can see her readings, but so that he cannot change her settings.

**Comment by fatyogi** [comment]
Hi Tamila,

My knowledge of Grafana is very basic. I suggest you have a look at Grafana
documentation regarding managing users and providing access to dashboards.
Pretty sure it is possible to have a read-only access to a particular
dashboard.

Thank you for your comments.

Btw I have closed this issue, if you have some more questions please open a
new one in GitHub.

// Laconic style, sent from my phone
